export const ASSOCIATION_LABEL_TEXT_SELECTOR = "ASSOCIATION_LABEL_TEXT_SELECTOR"
export const COLUMN_PORT_SELECTOR = "COLUMN_PORT_SELECTOR"
export const COLUMN_PORT_GROUP = "COLUMN_PORT_GROUP"
export const COLUMN_PORT = "COLUMN_PORT"
export const SWITCH_ASSOCIATION_FLAG = "SWITCH_ASSOCIATION_FLAG"
export const COLUMN_HEIGHT = 30
export const COLUMN_INIT_WIDTH = 200
