// 样式常量
export const COLUMN_PORT_SELECTOR = "COLUMN_PORT_SELECTOR"
export const COLUMN_PORT_GROUP = "COLUMN_PORT_GROUP"
export const COLUMN_PORT = "COLUMN_PORT"
export const COLUMN_HEIGHT = 30
export const COLUMN_INIT_WIDTH = 200

// ASSOCIATION_TYPE 常量
export const SWITCH_ASSOCIATION_TYPE_FLAG = "SWITCH_ASSOCIATION_TYPE_FLAG"
export const ASSOCIATION_LABEL_TEXT_SELECTOR = "ASSOCIATION_LABEL_TEXT_SELECTOR"

// ASSOCIATION_FAKE 常量
export const SWITCH_ASSOCIATION_FAKE_FLAG = "SWITCH_ASSOCIATION_FAKE_FLAG"
