export const GenerateTag_CONSTANTS = [
    'BackEnd', 
    'DDL', 
    'Enum', 
    'Entity', 
    'DTO', 
    'Permission', 
    'Route', 
    'Service', 
    'CrudTest', 
    'FrontEnd', 
    'Component', 
    'Rules', 
    'EnumView', 
    'EnumSelect', 
    'IdSelect', 
    'Page', 
    'Form', 
    'FormDefault', 
    'FormType', 
    'ViewForm', 
    'QueryForm', 
    'AddForm', 
    'EditForm', 
    'ViewTable', 
    'EditTable', 
    'SubEdit', 
    'SubView'
] as const;
export type GenerateTag = typeof GenerateTag_CONSTANTS[number];
