export const GenerateTag_CONSTANTS = [
    'BackEnd', 
    'Table', 
    'Enum', 
    'Entity', 
    'DTO', 
    'Permission', 
    'Route', 
    'Service', 
    'FrontEnd', 
    'Component', 
    'EnumView', 
    'EnumSelect', 
    'EnumNullableSelect', 
    'IdSelect', 
    'IdMultiSelect', 
    'Page', 
    'AddForm', 
    'EditForm', 
    'EditTable', 
    'QueryForm', 
    'AddFormDataType', 
    'DefaultAddFormData', 
    'Rules', 
    'AddFormRules', 
    'EditFormRules', 
    'EditTableRules'
] as const;
export type GenerateTag = typeof GenerateTag_CONSTANTS[number];
